# Generated by Django 4.0.5 on 2023-03-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.CharField(default='', max_length=225),
        ),
    ]
