# Generated by Django 4.0.5 on 2023-03-14 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textAPI', '0002_complaint_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='textAPI.complaint'),
        ),
    ]
